import Head from "next/head";
import Image from "next/image";
import About from "../components/About";

import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Room Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/images/favicon-32x32.png" />
      </Head>
      <Navbar />
      <Hero />
      <About />
    </div>
  );
}
